### ISSUE TITLE
understanding requirement

### ISSUE THREAD

**Issue by AlanFor301** [CMPUT301F15T13/TheAllSwap#1]
I'm confused about the following US when composing our storyboard. If anyone can bring up clearer ideas, that would be great
US04.05.01

As a borrower or owner, when composing a trade or counter-trade I can edit the trade.

US01.07.01
As an owner, I want the entry of an item to have minimal required navigation in the user interface. It must be easy to describe an item.

**Comment by aozero** [comment]
US04.05.01: I would guess that this means that the user wants to be able to edit (replace, remove) the items for trade, the friend to trade with, etc, instead of just being able to add. So edit and remove buttons should be somewhere on the UI I suppose.

US01.07.01: They just want it to be simple to add and describe an item, so perhaps a title text box with a description right underneath it, nice and compact, rather than spreading things out all over or overcomplicating it (somehow).

**Comment by AlanFor301** [comment]
Agree. 
Thanks for help. 
Issue closed
