### ISSUE TITLE
is those two US are redundant?

### ISSUE THREAD

**Issue by AlanFor301** [CMPUT301F15T13/TheAllSwap#2]
US04.08.01

As an owner or borrower, I can browse all past and current trades involving me.

US04.09.01

As an owner or borrower, I can browse all past and current trades involving me as either borrower or owner. I should look at my trades and trades offered to me.

**Comment by aozero** [comment]
After reading them over a few times, I think the first is for viewing every trade a user has been a part of, and the second is for viewing trades that a user has either been only the borrower or only the owner of (either way, it displays both the trades they initiated and the trades they were offered, as whatever role).

**Comment by AlanFor301** [comment]
That makes much more sense. So shall we give the 'user' an option to choose the way the list are loaded?
1. random load (as long as the 'user' is involved)
2. As a borrower first.
3. As a owner first .

**Comment by aozero** [comment]
Yeah, essentially; I'd say give the choice to load:
1. All trades involving the user (I'm sure we'll have sort-by-date or something)
2. As a borrower only
3. As an owner only
I'd think it would be best to filter rather than sort, no? I would imagine it would be confusing for the user to scroll through trades you started and suddenly see one that someone else initiated.

**Comment by AlanFor301** [comment]
got it. issue closed
